import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ul className="flex gap-4  border-b  p-6 text-indigo-600 text-base font-semibold">
          <li>
            <Link className=" " href="/">
              Home
            </Link>
          </li>
          <li>
            <Link className=" " href="/number-to-word">
              Numbertoword
            </Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
